import 'package:cloud_firestore/cloud_firestore.dart';

int? _toInt(dynamic value) {
  if (value == null) {
    return null;
  }
  if (value is int) {
    return value;
  }
  if (value is double) {
    return value.toInt();
  }
  if (value is String) {
    return int.tryParse(value);
  }
  return null;
}

DateTime _toDateTime(dynamic value, {DateTime? fallback}) {
  if (value is Timestamp) {
    return value.toDate();
  }
  if (value is DateTime) {
    return value;
  }
  if (value is String) {
    return DateTime.tryParse(value) ?? fallback ?? DateTime.now();
  }
  return fallback ?? DateTime.now();
}

DateTime? _toNullableDateTime(dynamic value) {
  if (value == null) {
    return null;
  }
  if (value is Timestamp) {
    return value.toDate();
  }
  if (value is DateTime) {
    return value;
  }
  if (value is String) {
    return DateTime.tryParse(value);
  }
  return null;
}

/// Job lifecycle states for audio transcription and summarization pipeline
enum SpeechJobStatus {
  /// Audio file uploaded, awaiting transcription start
  uploaded,

  /// Transcription in progress (Whisper API)
  transcribing,

  /// Transcription completed, transcript text available
  transcribed,

  /// Summarization in progress (Groq API)
  summarizing,

  /// All tasks complete; transcript and summary available
  completed,

  /// Job failed; see [error] field for details
  failed,
}

/// Represents a single speech recording job tracking audio transcription and summarization
/// Persisted in Firestore at: users/{uid}/speech_jobs/{jobId}
/// Also indexed in main collection: speech_jobs/{jobId} for admin/analytics
class SpeechJob {
  /// Unique job identifier (UUID, generated by backend)
  final String id;

  /// Firebase UID of job owner (derived from auth token server-side)
  final String userId;

  /// Optional tournament ID if speech was recorded during a tournament
  final String? tournamentId;

  /// Current state in the job lifecycle
  SpeechJobStatus status;

  /// Duration of the original recording in seconds
  final int? durationSeconds;

  /// Transcribed text from audio (null until status >= transcribed)
  String? transcript;

  /// AI-generated summary of transcript (null until status == completed)
  String? summary;

  /// Error message if status == failed
  String? error;

  /// Firebase Storage path to uploaded audio file (e.g., speech_audio/{uid}/{jobId}.m4a)
  final String? audioStoragePath;

  /// Timestamp when job was created (audio uploaded)
  final DateTime createdAt;

  /// Timestamp when job transitioned to current status
  DateTime? updatedAt;

  /// Timestamp when all processing completed (status == completed or failed)
  DateTime? completedAt;

  SpeechJob({
    required this.id,
    required this.userId,
    this.tournamentId,
    this.status = SpeechJobStatus.uploaded,
    this.durationSeconds,
    this.transcript,
    this.summary,
    this.error,
    this.audioStoragePath,
    DateTime? createdAt,
    this.updatedAt,
    this.completedAt,
  }) : createdAt = createdAt ?? DateTime.now();

  /// Converts job to JSON for Firestore storage
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'tournamentId': tournamentId,
      'status': status.toShortString(),
      'durationSeconds': durationSeconds,
      'transcript': transcript,
      'summary': summary,
      'error': error,
      'audioStoragePath': audioStoragePath,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
      'completedAt':
          completedAt != null ? Timestamp.fromDate(completedAt!) : null,
    };
  }

  /// Creates SpeechJob from Firestore document data
  factory SpeechJob.fromJson(Map<String, dynamic> json) {
    return SpeechJob(
      id: json['id']?.toString() ?? '',
      userId: json['userId']?.toString() ?? '',
      tournamentId: json['tournamentId']?.toString(),
      status: (json['status']?.toString() ?? '').toSpeechJobStatus(),
      durationSeconds: _toInt(json['durationSeconds']),
      transcript: json['transcript']?.toString(),
      summary: json['summary']?.toString(),
      error: json['error']?.toString(),
      audioStoragePath: json['audioStoragePath']?.toString(),
      createdAt: _toDateTime(json['createdAt']),
      updatedAt: _toNullableDateTime(json['updatedAt']),
      completedAt: _toNullableDateTime(json['completedAt']),
    );
  }

  /// Creates a copy of this job with optional field updates
  SpeechJob copyWith({
    String? id,
    String? userId,
    String? tournamentId,
    SpeechJobStatus? status,
    int? durationSeconds,
    String? transcript,
    String? summary,
    String? error,
    String? audioStoragePath,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? completedAt,
  }) {
    return SpeechJob(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      tournamentId: tournamentId ?? this.tournamentId,
      status: status ?? this.status,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      transcript: transcript ?? this.transcript,
      summary: summary ?? this.summary,
      error: error ?? this.error,
      audioStoragePath: audioStoragePath ?? this.audioStoragePath,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      completedAt: completedAt ?? this.completedAt,
    );
  }

  /// Whether job is still processing
  bool get isProcessing =>
      status == SpeechJobStatus.transcribing ||
      status == SpeechJobStatus.summarizing;

  /// Whether job has finished (successfully or failed)
  bool get isFinished =>
      status == SpeechJobStatus.completed || status == SpeechJobStatus.failed;

  /// Human-readable status label for UI
  String get statusLabel {
    switch (status) {
      case SpeechJobStatus.uploaded:
        return 'Uploaded';
      case SpeechJobStatus.transcribing:
        return 'Transcribing...';
      case SpeechJobStatus.transcribed:
        return 'Transcribed';
      case SpeechJobStatus.summarizing:
        return 'Summarizing...';
      case SpeechJobStatus.completed:
        return 'Completed';
      case SpeechJobStatus.failed:
        return 'Failed';
    }
  }

  @override
  String toString() =>
      'SpeechJob(id=$id, userId=$userId, status=${status.toShortString()})';
}

/// Extension methods for SpeechJobStatus enum serialization
extension SpeechJobStatusExtension on SpeechJobStatus {
  /// Converts enum to short string name (e.g., 'uploaded')
  String toShortString() => toString().split('.').last;

  /// Whether this status represents a completed state (success or error)
  bool get isTerminal =>
      this == SpeechJobStatus.completed || this == SpeechJobStatus.failed;
}

/// Extension for parsing status string back to enum
extension SpeechJobStatusParsing on String? {
  /// Safely parses string to SpeechJobStatus enum
  SpeechJobStatus toSpeechJobStatus() {
    if (this == null || this!.isEmpty) {
      return SpeechJobStatus.uploaded;
    }
    try {
      return SpeechJobStatus.values
          .firstWhere((e) => e.toShortString() == this);
    } catch (e) {
      return SpeechJobStatus.uploaded;
    }
  }
}
